### ISSUE TITLE
Navigation bar color

### ISSUE THREAD

**Issue by nvllz** [ziadOUA/zCard#16]
As with Catima, I have a problem with the color of the navigation bar. It doesn't match the selected theme and with pure black it looks like this:

![](https://user-images.githubusercontent.com/110673332/251519365-e5af52be-1f4a-4162-b03c-ceb48e3e0b65.png)

It was fixed once, but the Catima developer found the fix buggy and reverted it. I expect the navigation bar to be black so it doesn't distract me.

I see this repo as a continuation, as there is a big mess in the original project, and hope you have some time to maintain it properly. Cheers!

**Comment by ziadOUA** [comment]
Hi @nvllz,

I'm going to look into this problem, and try to fix it.

Also, this repo isn't really a continuation, because Catima is still active, and also because this is the repo where I changed everything I didn't like too much about it. 

Thanks

**Comment by ziadOUA** [comment]
It is becoming a mess, 

The background color can be modified, but the icons don't seem to change (icons will remain white even on a white background).
There is a "workaround", but, not only it needs Android 8.1 (or higher), it doesn't seem to work on my phone (Android 13, Vivo).
I will need help on this one, you can try to open this issue on Catima (if it isn't already present)

**Comment by nvllz** [comment]
They also had a hard time with it, and eventually the main dev reverted this feature. I've linked some stackoverflow answers in the relative Catima issue topic, but there's no one to work on it. What about this one?
https://stackoverflow.com/a/66903838

I wonder how developers come up with this so easily, since it's hard to find a popular topic about it online. And many FOSS applications lack this feature because no one can figure it out. I'll try to seek for some additional advice on this.

Edit: What about testing some open source app and do some reverse engineering? If it's somewhere implemented correctly, you could try to make it work the same way in zCard :D

For me it works well with Aegis, ReadYou and LibreSudoku. Quillpad and Obtainium have white icons and transparent navigation bar for light theme, and dark/black works as intended in all the listed apps.

**Comment by ziadOUA** [comment]
I will see what I can do, even if I am new in the area

**Comment by nvllz** [comment]
Hi, I just found a commit fixing the navigation bar color for dark theme. I wonder if you'd be able to somehow make it work properly with zCard too. Check it out in your free time please: https://github.com/maxrave-dev/SimpMusic/commit/b97082a73e3b13adeb9f92cccaa141b841a2660f

**Comment by ziadOUA** [comment]
Hi @nvllz, Thanks for your research, this commit seems to relate, as far as I know, to the bottom navigation bar used to navigate between the different pages within the app. 
On my end, the navigation bar is black in both light and dark mode. Still trying various things to fix it, but my lack of knowledge in Java doesn't help.

**Comment by nvllz** [comment]
Hey, @ziadOUA. The https://github.com/ziadOUA/zCard/commit/b867b33f537c325b3ec9f3714bc28e5034efefd7 commit seems to break the thing for me in the light theme. It makes the navigation bar transparent with barely visible, white icons. The final version of my PR worked well on my side, idk why it's broken now. Sorry :/

**Comment by ziadOUA** [comment]
I'll look into it @nvllz

**Comment by TheLastProject** [comment]
You may want to have a look at https://github.com/CatimaLoyalty/Android/pull/1547, from my testing it works well

**Comment by ziadOUA** [comment]
Thanks, @TheLastProject
I reverted the changes I made to include the ones on Caatima. They seem to work, apart for the fact that the navigation bar doesn't use the same color on the main activity (it must just be an oddity on my part, but I don't use navigation buttons anyways).

**Comment by TheLastProject** [comment]
Fixed in https://github.com/CatimaLoyalty/Android/pull/1572. I forgot to test on the buttons, saw the colour change correctly with the gesture navigation and wrongly expected Android to, for once in its life, be consistent in behaviour. But nope, only gesture navigation magically does the correct thing, buttons do not.
